dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  on:
    all_branches: true
  skip_cleanup: true
  script:
  - curl -T cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ui-zil2017:$BINTRAY_API_KEY "https://api.bintray.com/content/zil2017/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64"
